### ISSUE TITLE
IPFS-Zeronet Testing

### ISSUE THREAD

**Issue by Teredic** [scala-network/scala-v7#28]
I got a small error while launching the zeronet argument...

Here's the details :  
2018-08-03 08:37:18.684 9508    INFO    global  src/daemon/main.cpp:279 Stellite 'Titanium v3' (v1.2.4.2-release)
2018-08-03 08:37:18.685 9508    INFO    global  src/daemon/protocol.h:55        Initializing cryptonote protocol...
2018-08-03 08:37:18.685 9508    INFO    global  src/daemon/protocol.h:60        Cryptonote protocol initialized OK
2018-08-03 08:37:18.697 9508    INFO    global  src/daemon/p2p.h:63     Initializing p2p server...
2018-08-03 08:37:21.013 9508    INFO    global  src/p2p/net_node.inl:426        Fetching seed list from ZeroNet/IPFS...
panic: interface conversion: interface {} is nil, not float64

goroutine 190 [running]:
github.com/donovansolms/ZeroGo/downloader.(*Downloader).Download(0xc042692280, 0xc0422567e0, 0x0, 0x0, 0x0)
        C:/GoPath/src/github.com/donovansolms/ZeroGo/downloader/downloader.go:72 +0x9ed
github.com/donovansolms/ZeroGo/site.(*Site).Download.func1(0xc042692200, 0xc0422567e0)
        C:/GoPath/src/github.com/donovansolms/ZeroGo/site/site.go:67 +0x9a
created by github.com/donovansolms/ZeroGo/site.(*Site).Download
        C:/GoPath/src/github.com/donovansolms/ZeroGo/site/site.go:60 +0xae

**Comment by donovansolms** [comment]
Thanks for testing!

I understand this is on Windows 10 correct? 
Do you have a firewall, VPN or proxy active when starting the daemon?

**Comment by Teredic** [comment]
Yeah that's right i'm under Windows 10.  Version 1803. And no i don't have any firewall/proxy nor a VPN.

But i have a NAT, but it should open automatically with UPNP ^_^

**Comment by donovansolms** [comment]
You're right, it should be fine. I'll attempt to replicate and get back to you.

**Comment by Teredic** [comment]
I've fixed the problem. I have deleted the "ipfs" and "zeronet" directories in "c:\programdata\stellite" and relaunched the .bat and it works now.
